resolver: lts-12.3
packages:
- .
extra-deps:
- 'prim-array-0.2.1'
- 'enum-types-0.1.1.0'
- 'quickcheck-classes-0.6.1.0'
- 'quickcheck-enum-instances-0.1.0.0'
- 'semirings-0.3.1.2'
flags: {}
extra-package-dbs: []
